AWSTemplateFormatVersion: "2010-09-09"
Description: Supporting Resources for the Sample Serverless API stack
Parameters:
  Environment:
    Description: The name of the environment being deployed.
    Type: String
    AllowedValues:
      - dev
      - test
      - stage
      - prod

Resources:

  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Sub "gotdp-${Environment}"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GS_Type"
          KeySchema:
              - AttributeName: "sk"
                KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "GS_Name"
          KeySchema:
              - AttributeName: "name"
                KeyType: "HASH"
              - AttributeName: "sk"
                KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
    