service: gotdp-consumerapi-lambdas

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-mocha-plugin

custom:
  serverless-offline:
    port: 3000
  
  defaults:
    stage: dev
    region: us-west-1

  apiGateway:
    restApiId:
      "Fn::ImportValue": "ConsumerApi-${self:custom.stage}-${self:custom.region}-ApiGatewayRestApi-RestApiId"
    restApiRootResourceId:
      "Fn::ImportValue": "ConsumerApi-${self:custom.stage}-${self:custom.region}-ApiGatewayRestApiResourceV1-Id"
  lambda:
    defaultRole:
      "Fn::ImportValue": "ConsumerApi-${self:custom.stage}-${self:custom.region}-DefaultLambdaRole-Arn"
    defaultTimeout: 30
    namePrefix: "gotdp-consumerapi-${self:custom.stage}-"
  stackName: ${self:custom.stage}-${self:service} 
  stage: ${opt:stage,self:custom.defaults.stage}
  region: ${opt:region,self:custom.defaults.region}
  webpack:
    webpackConfig: webpack.config.js   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: npm   # Packager that will be used to package your external modules
    packExternalModulesMaxBuffer: 200 * 1024   # Size of stdio buffers for spawned child processes

provider:
  name: aws
  runtime: nodejs8.10
  stackName: ${self:custom.stackName}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  timeout: ${self:custom.lambda.defaultTimeout}
  apiGateway:
    restApiId: ${self:custom.apiGateway.restApiId}
    restApiRootResourceId: ${self:custom.apiGateway.restApiRootResourceId}
  role: ${self:custom.lambda.defaultRole}
  environment:
    GOTDP_DYNAMO_TABLE: "gotdp-${self:custom.stage}"
  
# package:
#   individually: true

functions:
  getCharacters:
    handler: lambdas/getCharacters.handler
    name: ${self:custom.lambda.namePrefix}getCharacters
    events:
      - http:
          path: characters
          method: get
          cors: true
          private: false

  getQuestions:
    handler: lambdas/getQuestions.handler
    name: ${self:custom.lambda.namePrefix}getQuestions
    events:
      - http:
          path: questions
          method: get
          cors: true
          private: false
  
  getUser:
    handler: lambdas/getUser.handler
    name: ${self:custom.lambda.namePrefix}getUser
    events:
      - http:
          path: user/{name}
          method: get
          cors: true
          private: false
          request:
            parameters:
              paths:
                name: true
              querystrings:
                withHistory: false
  
  getUsers:
    handler: lambdas/getUsers.handler
    name: ${self:custom.lambda.namePrefix}getUsers
    events:
      - http:
          path: users
          method: get
          cors: true
          private: false
  
  healthcheck:
    handler: lambdas/healthcheck.handler
    name: ${self:custom.lambda.namePrefix}healthcheck
    events:
      - http:
          path: healthcheck
          method: get
          cors: true
          private: false
    environment:
      STATUS: 'ok'
  
  patchQuestion:
    handler: lambdas/patchQuestion.handler
    name: ${self:custom.lambda.namePrefix}patchQuestion
    events:
      - http:
          path: question
          method: patch
          cors: true
          private: false
  
  putUser:
    handler: lambdas/putUser.handler
    name: ${self:custom.lambda.namePrefix}putUser
    events:
      - http:
          path: user
          method: put
          cors: true
          private: false
  
  refreshCharacters:
    handler: lambdas/refreshCharacters.handler
    name: ${self:custom.lambda.namePrefix}refreshCharacters
    events:
      - schedule: "cron(4/15 * ? * SUN-MON *)"
  
  refreshQuestions:
    handler: lambdas/refreshQuestions.handler
    name: ${self:custom.lambda.namePrefix}refreshQuestions
  
  refreshUsers:
    handler: lambdas/refreshUsers.handler
    name: ${self:custom.lambda.namePrefix}refreshUsers
    events:
      - schedule: "cron(7/15 * ? * * *)"
